//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PokerLeagueManager.Commands.Domain.QueryServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="QueryServiceReference.IQueryService")]
    public interface IQueryService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IQueryService/GetGameCountByDate", ReplyAction="http://tempuri.org/IQueryService/GetGameCountByDateResponse")]
        int GetGameCountByDate(System.DateTime gameDate);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IQueryService/GetGameCountByDate", ReplyAction="http://tempuri.org/IQueryService/GetGameCountByDateResponse")]
        System.Threading.Tasks.Task<int> GetGameCountByDateAsync(System.DateTime gameDate);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IQueryServiceChannel : PokerLeagueManager.Commands.Domain.QueryServiceReference.IQueryService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class QueryServiceClient : System.ServiceModel.ClientBase<PokerLeagueManager.Commands.Domain.QueryServiceReference.IQueryService>, PokerLeagueManager.Commands.Domain.QueryServiceReference.IQueryService {
        
        public QueryServiceClient() {
        }
        
        public QueryServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public QueryServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public QueryServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public QueryServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public int GetGameCountByDate(System.DateTime gameDate) {
            return base.Channel.GetGameCountByDate(gameDate);
        }
        
        public System.Threading.Tasks.Task<int> GetGameCountByDateAsync(System.DateTime gameDate) {
            return base.Channel.GetGameCountByDateAsync(gameDate);
        }
    }
}
