name: CI Workflow

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: windows-latest
    env:
      BuildConfiguration: Release
      BuildPlatform: 'Any CPU'

    steps:
    - uses: actions/checkout@v2
    
    - name: Version Assemblies
      run: ./deploy/VersionAssemblies.ps1 -MajorVersion 0 -MinorVersion 1 -BuildNumber $env:GITHUB_RUN_NUMBER -SourcesDir . -Verbose
      shell: powershell
      
    - name: Install Nuget
      uses: nuget/setup-nuget@v1
      with:
        nuget-version: latest

    - name: NuGet Restore
      run: nuget restore ./src/PokerLeagueManager.sln
  
    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1.0.0
    
    - name: Setup Node
      uses: actions/setup-node@v1.1.0
      with:
        node-version: 12.x
    
    - name: npm ci
      run: npm ci
      working-directory: ./src/PokerLeagueManager.UI.Web/angular
      
    - name: Generate TypeScript Lib
      run: GenerateTypeScript.bat
      working-directory: ./src/PokerLeagueManager.UI.Web
      shell: cmd
      
    - name: Build Angular
      run: npm run build-prod
      working-directory: ./src/PokerLeagueManager.UI.Web/angular
      
    - name: Create index.cshtml
      run: ./deploy/TransformIndex.ps1 -SourcePath ./src/PokerLeagueManager.UI.Web/angular/dist/index.html -TargetPath ./src/PokerLeagueManager.UI.Web/angular/dist/index.cshtml
      shell: powershell
    
    - name: Run Jasmine Tests
      run: npm run test-prod
      working-directory: ./src/PokerLeagueManager.UI.Web/angular
    
    - name: Build Solution
      run: msbuild ./src/PokerLeagueManager.sln /p:TreatWarningsAsErrors=true /p:CodeAnalysisRuleSet="../PokerLeagueManager.ruleset" /p:DeployOnBuild=true /p:WebPublishMethod=Package /p:PackageAsSingleFile=true /p:ValidateArchitecture=true /p:"platform=$env:BuildPlatform" /p:configuration="$env:BuildConfiguration"
      
    - name: Setup VSTest
      uses: Malcolmnixon/Setup-VSTest@v2
      
    - name: Run Unit Tests
      run: vstest.console "src\PokerLeagueManager.Commands.Tests\bin\Release\PokerLeagueManager.Commands.Tests.dll" "src\PokerLeagueManager.Infrastructure.Tests\bin\Release\PokerLeagueManager.Infrastructure.Tests.dll" "src\PokerLeagueManager.Queries.Tests\bin\Release\PokerLeagueManager.Queries.Tests.dll" /Logger:"trx" /Parallel /Blame

    - name: Copy QueryStore Artifacts
      run: "Copy-Item -Path 'db/QueryStore/*' -Destination (New-Item -Path 'drop/DB.QueryStore/' -Type Directory)"
      shell: powershell
      
    - name: Copy EventStore Artifacts
      run: "Copy-Item -Path 'db/EventStore/*' -Destination (New-Item -Path 'drop/DB.EventStore/' -Type Directory)"
      shell: powershell

    - name: Publish Artifacts
      uses: actions/upload-artifact@v1.0.0
      with:
        name: drop
        path: ./drop
